# Check for duplicates in titles and authors of the papers from the References in endnote

 Aim is to write a function using the dedupe and turn it to an application for deduplicating the records obtained from databases on the basis of titles

In [12]:
#install pandas-dedupe
# !pip install pandas-dedupe #completed installation

In [5]:
#import pandas and dedupe libraries

In [24]:
import pandas as pd #importing pandas
import pandas_dedupe

In [25]:
#read in the dataframe

dt = pd.read_csv("./Dedup/whitehouse-waves-2014_03.csv")
dt

/var/folders/pn/sqv4n6ms0hnchhr2ll3kh5x00000gq/T/ipykernel_73913/3653918953.py:3: DtypeWarning: Columns (13,26) have mixed types. Specify dtype option on import or set low_memory=False.
  dt = pd.read_csv("./Dedup/whitehouse-waves-2014_03.csv")

,NAMELAST,NAMEFIRST,NAMEMID,UIN,BDGNBR,ACCESS_TYPE,TOA,POA,TOD,POD,...,TERMINAL_SUFFIX,visitee_namelast,visitee_namefirst,MEETING_LOC,MEETING_ROOM,CALLER_NAME_LAST,CALLER_NAME_FIRST,CALLER_ROOM,description,RELEASE_DATE
0,Aalami,Arianna,N,U44019,NaN,VA,NaN,NaN,NaN,NaN,...,JC,OFFICE,VISITORS,WH,RESIDENCE,OFFICE,VISITORS,NaN,NaN,4/25/2014
1,Aalami,Florian,B,U44019,NaN,VA,NaN,NaN,NaN,NaN,...,JC,OFFICE,VISITORS,WH,RESIDENCE,OFFICE,VISITORS,NaN,NaN,4/25/2014
2,Aalami,Sophia,J,U44019,NaN,VA,NaN,NaN,NaN,NaN,...,JC,OFFICE,VISITORS,WH,RESIDENCE,OFFICE,VISITORS,NaN,NaN,4/25/2014
3,Aaland,Neil,L,U44410,NaN,VA,NaN,NaN,NaN,NaN,...,JC,OFFICE,VISITORS,WH,RESIDENCE,OFFICE,VISITORS,NaN,F,4/25/2014
4,Aalemansour,Hannah,NaN,U51535,NaN,VA,NaN,NaN,NaN,NaN,...,CB,NaN,POTUS,WH,SOUTH LAWN,OFFICE,VISITORS,NaN,NaN,5/30/2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164394,Schermann,Jon,H,U66252,0.0,VA,3/31/2014 19:17,B0401,NaN,NaN,...,LJ,Chiu,Melissa,OEOB,37,JONES,LISA,NaN,NaN,6/27/2014
164395,Schield,Brieana,R,U66252,0.0,VA,3/31/2014 19:17,B0401,NaN,NaN,...,LJ,Chiu,Melissa,OEOB,37,JONES,LISA,NaN,NaN,6/27/2014
164396,SchieldPrice,Jonah,J,U66252,0.0,VA,3/31/2014 19:17,B0401,NaN,NaN,...,LJ,Chiu,Melissa,OEOB,37,JONES,LISA,NaN,NaN,6/27/2014
164397,Karas,Barry,NaN,U68214,98020.0,VA,3/31/2014 18:51,A0401,NaN,NaN,...,BM,Mosteller,Brian,WH,WW,MOSTELLER,BRIAN,NaN,NaN,6/27/2014
164398,Smith,Brian,P,U68214,102709.0,VA,3/31/2014 18:51,A0401,NaN,NaN,...,BM,Mosteller,Brian,WH,WW,MOSTELLER,BRIAN,NaN,NaN,6/27/2014

In [26]:
#help(pandas_dedupe.dedupe_dataframe)
dF = pandas_dedupe.dedupe_dataframe(dt, ['NAMELAST','NAMEFIRST','NAMEMID'])

Importing data ...

/var/folders/pn/sqv4n6ms0hnchhr2ll3kh5x00000gq/T/ipykernel_73913/4009574177.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  dF = pandas_dedupe.dedupe_dataframe(dt, ['NAMELAST','NAMEFIRST','NAMEMID'])

Reading from dedupe_dataframe_learned_settings
Clustering...
# duplicate sets 122967

In [29]:
dF.to_csv('./Dedup/test.csv')

In [35]:
emb_coch_med_df = pandas_dedupe.dedupe_dataframe(emb_coch_med, ["Year","Title","Accessionnumber"])

Importing data ...
Reading from dedupe_dataframe_learned_settings
Clustering...

/var/folders/pn/sqv4n6ms0hnchhr2ll3kh5x00000gq/T/ipykernel_73913/3104604941.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  emb_coch_med_df = pandas_dedupe.dedupe_dataframe(emb_coch_med, ["Year","Title","Accessionnumber"])

KeyError: 'NAMELAST'